config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :lessons, :assignments
end

app/views/shared/_dotw.html.erb
<div class="column">
  <div class="box">
    <p class="title is-size-4 is-size-6-mobile has-text-<%= color %>"><%= day %>:</p>
    <ul>
      <% @lessons.each do |lesson| %>

        <% if lesson.date == day %>
          <li>
            <div class="is-flex">
              
              <% if current_user.id == lesson.user_id %>
                <%= link_to lesson.info, lesson_path(lesson.id), class: "has-text-black is-size-7-mobile" %> 
              <% end %>
              
              <% lesson.assignments.each do |assignment| %>
                <% if assignment.time_remaining <= 7 && current_user.id == lesson.user_id %>
                  <div class="has-text-danger-dark ml-2 is-size-7-mobile">Order new homework!</div>
                <% end %>
              <% end %>
              
            </div>
          </li>
        <% end %>
      <% end %>
      </li>
    </ul>          
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'notice' %>
    <div class="notification is-primary">
      <%= msg %>
    </div>
  <% else %>
    <div class="notification is-danger">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_lesson_form.html.erb
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-content-center">
  <h1 class="title"><%= title %></h1>


  <%= form_with model: @lesson do |f| %>
    <div class="container is-flex">
      <%= f.label :rank, "Rank:", class: "label" %>
      <%= f.select :rank, ['10th Rank', '9th Rank', '8th Rank',
                            '7th Rank', '6th Rank', '5th Rank',
                            '4th Rank', '3rd Rank', '2nd Rank',
                            '1st Rank', 'Returnee', 'Private Adult', 'Private Child',
                            'Private Group'], {}, class: "select mx-2" %>
      <%= f.label :date, "Date:", class: "label" %>
      <%= f.select :date, ['Irregular', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], {}, class: "select mx-2" %>
    </div>

    <br>
    <div class="container is-flex">
      <%= f.label :time, "Time:", class: "label" %>
      <%= f.time_field :time, required: true, class: "input mx-2" %>
    </div>
    
    <br>

    <%= f.fields_for :assignments do |sf| %>
      <div class="is-flex">
        <%= sf.label :name, "Name:", class: "label" %>
        <%= f.select :name, Assignment.names, {}, class: "select mx-2" %>
        <%= sf.label :length, "Length(weeks):", class: "label" %>
        <%= sf.number_field :length, class: "input mx-2 mb-4" %>
      </div>
    <% end %>

    <div class="container is-flex is-flex-direction-column is-justify-content-center is-align-content-center">
      <%= f.submit "Submit", class: "button is-rounded is-primary" %>
    </div>
    
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar has-background-light pt-5 pb-5 pl-2 pr-2">
  <div class="navbar-brand">
    <div class="navbar-item">
      <%= link_to "Homework Planner", root_path, class: "title has-text-black" %>
    </div>

    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

<div class="navbar-menu" id="navMenu">

    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to "New Lesson", new_lesson_path, class: "has-text-black" %>
      </div>

      <div class="navbar-item">
        <%= link_to "View Lessons", lessons_path, class: "has-text-black" %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <%= button_to "Edit Profile", edit_user_registration_path, class: "button is-small is-rounded is-primary", method: :get %>
      </div>
      
      <div class="navbar-item">
        <%= button_to "Log out", destroy_user_session_path, class: "button is-small is-rounded is-danger", method: :delete %>
      </div>
    </div>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {

      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');

    });
  });

});
</script>