config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :lessons, :assignments
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :rank, :time, :date, presence: true
  has_many :assignments
  accepts_nested_attributes_for :assignments

  def info
    "#{time.to_s[10..15]} - #{rank}"
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :lesson_owner, only: [:show, :edit, :destroy]

  def index
    @lessons = Lesson.all.order(time: :asc)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_user.lessons.build(lesson_params)

    if @lesson.save
      flash.notice = 'Lesson successfully created!'
      Assignment.warning_list
      redirect_to @lesson
    else
      flash.alert = 'Something went wrong!'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update(lesson_params)
      flash.notice = 'Lesson successfully updated!'
      redirect_to @lesson
    else
      flash.alert = 'Something went wrong!'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash.alert = 'Lesson deleted!'

    redirect_to root_path, status: :see_other
  end

  private

  def lesson_params
    params.require(:lesson).permit(:rank, :time, :date, assignments_attributes: [:name, :length, :id])
  end

  def lesson_owner
    lesson = Lesson.find(params[:id])
    lesson_user_id = lesson.user_id

    return if lesson_user_id == current_user.id

    flash.alert = 'This is not your lesson!'
    redirect_to root_path
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/edit.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<%= render "shared/lesson_form", title: "Edit Lesson:" %>

app/views/lessons/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<div class="columns is-flex is-flex-direction-column m-6">
  <%= render partial: "shared/dotw", :locals => { :day => 'Tuesday', :color => 'primary' } %>
  <%= render partial: "shared/dotw", :locals => { :day => 'Wednesday', :color => 'link' } %>
  <%= render partial: "shared/dotw", :locals => { :day => 'Thursday', :color => 'info' } %>
  <%= render partial: "shared/dotw", :locals => { :day => 'Friday', :color => 'success-dark' } %>
  <%= render partial: "shared/dotw", :locals => { :day => 'Saturday', :color => 'warning-dark' } %>
  <%= render partial: "shared/dotw", :locals => { :day => 'Irregular', :color => 'danger' } %>
</div>

app/views/lessons/new.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<%= render "shared/lesson_form", title: "New Lesson:" %>

app/views/lessons/show.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<div class="box m-6 is-flex is-flex-direction-column">
  <div class="title is-size-4-mobile"><%= @lesson.info %></div>
  
  <ul>
    <% @lesson.assignments.each do |assignment| %>
        <li>
          <div class="is-flex">
            <p class="m-2 is-size-7-mobile"><%= assignment.info %></p>
            <% if current_user.id == @lesson.user_id %>
              <%= button_to "x", assignment_path(assignment.id), class: "button is-small is-rounded is-danger m-2", method: :delete %>
            <% end %>
          </div>
        </li>
    <% end %>
  </ul>

  <% if current_user.id == @lesson.user_id %>
    <div class="is-flex mt-6 is-justify-content-right">
      <%= button_to "Delete lesson", lesson_path(@lesson), class: "button is-small is-rounded is-danger", method: :delete %>
      <%= button_to "Edit lesson", edit_lesson_path, class: "button is-small is-rounded is-primary ml-2", method: :get %>
    </div>
  <% end %>  
</div>

<% if current_user.id == @lesson.user_id %>
  <div class="box m-6 is-flex is-flex-direction-column">
    <h2 class="title m-2 is-size-4-mobile">New Homework:</h1>
    <div class="is-flex">
      <%= form_with model: Assignment.new do |f| %>
        <div class="is-flex is-flex-direction-column my-5">
          <%= f.label :name, "Homework:", class: "label is-size-7-mobile" %>
          <%= f.select(:name, Assignment.names, {}, required: true, class: "select") %>

          <%= f.label :length, "Length(weeks):", class: "label is-size-7-mobile mt-3"%>
          <%= f.number_field :length, required: true, class: "input" %>

          <%= f.hidden_field :lesson_id, value: @lesson.id %>
        </div>
        <%= f.submit 'New Homework', class: "button is-small is-rounded" %>
      <% end %>
    </div>
  </div>
<% end %>